services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      args:
        - CODE_DIR=${DOCKER_CODE_DIR}
        - DOCKER_WORLD_PORT=${DOCKER_WORLD_PORT}
    # command: tail -f /dev/null
    command: gunicorn home.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:${DOCKER_CODE_DIR}/staticfiles
      - ./backend/database:${DOCKER_CODE_DIR}/app/database
    expose:
      - 8000
    env_file:
      - .env.django_prod
  nginx:
    restart: always
    build: ./nginx
    ports:
      - ${DOCKER_WORLD_PORT}:8080
    depends_on:
      - web
    volumes:
      - static_volume:/home/django/staticfiles

volumes:
  static_volume:
