# Generated by Django 4.2.1 on 2023-05-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                (
                    "todo_verb",
                    models.CharField(help_text="verb, eg 'to watch'", max_length=50),
                ),
                (
                    "done_verb",
                    models.CharField(
                        help_text="verb, past tense, eg 'watched'", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("is_chosen", models.BooleanField(default=False)),
                ("is_done", models.BooleanField(default=False)),
                ("done_date", models.DateField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="jar.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="jaritem",
            constraint=models.UniqueConstraint(
                fields=("slug", "category"), name="Category-slug constraint"
            ),
        ),
    ]
